# Generated by Django 5.0.2 on 2024-03-08 14:13

import datetime
from django.db import migrations, models
import pytz


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 14, 13, 28, 989521, tzinfo=pytz.UTC)),
        ),
    ]
